# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Matan Goldman's Website
tagline:          'Deep learning and more'
description:      'A personal website'
url:              http://mtngld.github.io
baseurl:          /

author:
  name:           'Matan Goldman'
  url:            https://twitter.com/mtngld

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mtngld/mtngld.github.io
